version: '3'
services:
  app:
    container_name: "api-dev-container"
    environment:
      - DB_URI=mongodb://mongo:27017/easyclass
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app            # bind container's src folder to local files in order to enable webpack hot reload feature
      - /usr/src/app/node_modules # disables bind just for the container's 'node_modules' folder since it is specific to the container's specs (i.e. linux, etc)
    links:
      - mongo

  test:
    container_name: "api-test-container"
    environment:
      - DB_URI_TEST=mongodb://mongo:27017/easyclasstest
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app            # bind container's src folder to local files in order to enable webpack hot reload feature
      - /usr/src/app/node_modules # disables bind just for the container's 'node_modules' folder since it is specific to the container's specs (i.e. linux, etc)
    command: ["npm", "test"]
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"


